# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'Carlor' do
pod "AFNetworking", "~> 2.0"
pod "KVOController"
end

target 'CarlorTests' do

end

